accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/create/', views.create_profile, name='create_profile'),
    path('profile/', views.profile_detail, name='profile_detail'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

cafe/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('menu/', include('menu.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'),
         namespace='accounts')),
    path('reservations/',
         include('reservations.urls', namespace='reservations')),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('reserve/', views.reserve_table, name='reserve_table'),
    path('user_reservations/',
         views.user_reservations, name='user_reservations'),
    path('cancel_reservation/<int:reservation_id>/',
         views.cancel_reservation, name='cancel_reservation'),
    path('make_reservation/', views.reserve_table, name='make_reservation'),
    path('reserve_confirmation/',
         views.reserve_table, name='reserve_confirmation'),
    path('edit/<int:reservation_id>/',
         views.edit_reservation, name='edit_reservation'),
]

reservations/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Define the choices tuple
numb_of_guest_choices = (
    (1, "1 guest"),
    (2, "2 guests"),
    (3, "3 guests"),
    (4, "4 guests"),
    (5, "5 guests"),
    (6, "6 guests"),
    (7, "7 guests"),
    (8, "8 guests"),
)

times_for_reservation = (
    (datetime.time(7, 0), '7:00 AM'),
    (datetime.time(9, 0), '9:00 AM'),
    (datetime.time(11, 0), '11:00 AM'),
    (datetime.time(13, 0), '1:00 PM'),
    (datetime.time(15, 0), '3:00 PM'),
    (datetime.time(17, 0), '5:00 PM'),
    (datetime.time(19, 0), '7:00 PM'),
    (datetime.time(21, 0), '9:00 PM'),
    )


class Reservation(models.Model):
    """
    Represents a reservation with a user, date, time, and number of guests.
    Includes predefined choices for time slots and guest numbers.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField(choices=times_for_reservation)
    number_of_guests = models.IntegerField(choices=numb_of_guest_choices)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Resevation for {
            self.user.username} on {self.date} at {self.time}"

reservations/forms.py
# reservations/forms.py
from django import forms
from .models import Reservation


class CustomTimeInput(forms.TimeInput):
    """
    Custom widget for time input to ensure consistent formatting and user experience.
    """
    input_type = 'time'

    def format_value(self, value):
        if isinstance(value, str):
            return value
        return value.strftime('%H:%M') if value else ''


class ReservationForm(forms.ModelForm):
    """
    Form for creating or updating reservations with custom widgets for date and time fields.
    """
    class Meta:
        model = Reservation
        fields = ['date', 'time', 'number_of_guests']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

reservations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReservationForm
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .models import Reservation
from django.db import transaction
from django.utils import timezone


@login_required
def reserve_table(request):
    """
    Allows logged-in users to make a table reservation.
    Validates the form data to ensure,
    no double bookings for the same date and time.
    Sends a confirmation email upon successful reservation,
    and displays a confirmation page.
    """
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user

            # Check if reservation exists for the selected date and time
            existing_reservation = Reservation.objects.filter(
                date=reservation.date, time=reservation.time).exists()

            if existing_reservation:
                return render(request,
                              'reservations/reserve_exists.html',
                              {
                                  'date': reservation.date,
                                  'time': reservation.time
                              })

            with transaction.atomic():
                reservation.save()

            # As my userstory, I want to send confirmation email to user
            # using users email that was registered on sign up
            subject = 'Reservation Confirmation'
            message = (
                f'Your reservation details:\n'
                f'Number of Guests: {reservation.number_of_guests}\n'
                f'Date: {reservation.date}\n'
                f'Time: {reservation.time}'
            )
            from_email = 'bryarosman.bo@gmail.com'
            recipient_list = [request.user.email]

            send_mail(
                subject,
                message,
                from_email,
                recipient_list,
                fail_silently=False,
            )

            context = {
                'number_of_guests': reservation.number_of_guests,
                'date': reservation.date,
                'time': reservation.time,
            }
            # Redirects to new URL:
            return render(request, 'reservations/reserve_confirmation.html',
                          context)
    else:
        form = ReservationForm(initial={'name': request.user.username})
    return render(request, 'reservations/reserve_table.html', {'form': form})


@login_required
def user_reservations(request):
    """
    Displays a list of all reservations made by the logged-in user,
    visible on their profile page.
    """
    reservations = Reservation.objects.filter(user=request.user)
    return render(request,
                  'accounts/profile_detail.html',
                  {'reservations': reservations})


@login_required
def edit_reservation(request, reservation_id):
    """
    Allows users to edit their reservation details,
    given the reservation date is more than 2 days ahead.
    If the reservation date is less than 2 days, then
    editing is not allowed and a specific page is shown to guide user.
    """
    reservation = get_object_or_404(
     Reservation, id=reservation_id, user=request.user)

    difference = (reservation.date - timezone.now().date()).days

    if difference < 2:
        return render(request,
                      'reservations/cancel_not_allowed.html',
                      {'reservation': reservation})

    if request.method == 'POST':
        form = ReservationForm(request.POST, instance=reservation)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile_detail')
    else:
        form = ReservationForm(instance=reservation)
    return render(request,
                  'reservations/edit_reservation.html', {'form': form})


@login_required
def cancel_reservation(request, reservation_id):
    """
    Enables users to cancel their reservations,
    user can only cancel if the reservation date is less than 2 days away.
    Sends a cancellation confirmation email upon successful cancellation.
    """
    reservation = get_object_or_404(
        Reservation, id=reservation_id, user=request.user)

    difference = (reservation.date - timezone.now().date()).days

    if request.method == 'POST':

        if difference < 2:
            return render(request,
                          'reservations/cancel_not_allowed.html',
                          {'reservation': reservation})

        # send cancellation email to user
        subject = 'Cancellation Confirmed!'
        message = (
            f'Your reservation for {reservation.date} at '
            f'{reservation.time} has been canceled'
        )

        from_email = 'bryarosman.bo@gmail.com'
        recipient_list = [request.user.email]

        send_mail(
            subject,
            message,
            from_email,
            recipient_list,
            fail_silently=False,
        )

        reservation.delete()
        # Add a success message here if you want
        return redirect('accounts:profile_detail')
    return render(request,
                  'reservations/cancel_reservation.html',
                  {'reservation': reservation})

reservations/templates/reservations/cancel_not_allowed.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Unable to Cancel or Edit Reservation</h1>
    <p>Kindly be advised that you are unable to cancel or edit this reservation as the deadline has passed. Reservations cannot be cancelled and changed within 2 days of the reservation date.</p>
    <p>Please note that a cancellation fee of 5€ will apply if you cancel or edit your reservation.</p>
    <p>If you still wish to cancel or edit your reservation, please <a href="{% url 'contact' %}">Contact</a> us directly.</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'accounts:profile_detail' %}" class="btn btn-outline-dark">Go Back</a>
    </form>
</div>
{% endblock %}

reservations/templates/reservations/cancel_reservation.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Cancel Reservation</h1>
    <p>Are you sure you want to cancel the reservation for {{ reservation.user.username}} on {{reservation.date}} at {{ reservation.time}}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Cancel</button>
        <a href="{% url 'accounts:profile_detail' %}" class="btn btn-secondary">No, Go Back</a>
    </form>
</div>
{% endblock %}

reservations/templates/reservations/edit_reservation.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h2>Edit Reservation</h2>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Save Changes</button>
      </form>
    </div>
  </div>
</div>
<!-- JavaScript to disable past dates and set minimum date to tomorrow -->
<script>
  window.addEventListener("DOMContentLoaded", function () {
    var today = new Date();
    var tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    var tomorrowISO = tomorrow.toISOString().split("T")[0];
    document.getElementById("id_date").setAttribute("min", tomorrowISO);
  });
</script>

{% endblock %}

reservations/templates/reservations/reserve_confirmation.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Reservation Confirmation
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text-center">Reservation Confirmed!</h1>
            <div class="alert alert-success" role="alert">
                Congratulations! Your reservation has been successfully created.
            </div>
            <h2>Reservation Details:</h2>
            <ul>
                <li><strong>Number of Guests:</strong> {{ number_of_guests }}</li>
                <li><strong>Date:</strong> {{ date }}</li>
                <li><strong>Time:</strong> {{ time }}</li>
            </ul>
            <p>We appreciate you choosing Café Sahara & Beans for your upcoming visit. We're excited to welcome you!</p>
            <p>Warm regards,<br>/team Café Sahara & Beans</p>
            <a class="btn btn-outline-dark" href="{% url 'home' %}">Navigate back to Home</a>
            <a href="{% url 'accounts:profile_detail' %}" class="btn btn-outline-success">My reservations</a>
        </div>
    </div>
</div>

{% endblock %}

reservations/templates/reservations/reserve_exists.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Reservation Confirmation
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="alert alert-danger" role="alert">
                Unfortunately, the following date and time is already taken:
                <ul>
                    <li><strong>Date:</strong> {{ date }}</li>
                    <li><strong>Time:</strong> {{ time }}</li>
                </ul>
            </div>
            <p>Try again:</p><a class="btn btn-dark btn-sm" href="{% url 'reservations:reserve_table' %}"> Make Reservation</a>
            <a href="{% url 'accounts:profile_detail' %}" class="btn btn-outline-dark btn-sm">My reservations</a>
        </div>
    </div>
</div>

{% endblock %}

reservations/templates/reservations/reserve_table.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5 reservation_form">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text-center">Reserve a Table</h1>
            <form method="post" action="{% url 'reservations:make_reservation' %}">
                {% csrf_token %}
                {{ form|crispy }}

                <!-- JavaScript to disable past dates and set minimum date to tomorrow -->
                <script>
                    window.addEventListener('DOMContentLoaded', function () {
                        var today = new Date();
                        var tomorrow = new Date(today);
                        tomorrow.setDate(tomorrow.getDate() + 1);
                        var tomorrowISO = tomorrow.toISOString().split('T')[0];
                        document.getElementById('id_date').setAttribute('min', tomorrowISO);
                    });
                </script>

                <div class="text-center">
                    <!-- Display different content based on user profile existence -->
                    {% if user.profile %}
                        <button type="submit" class="btn btn-outline-dark">Create a Reservation</button>
                    {% else %}
                        <a href="{% url 'accounts:create_profile' %}" class="btn btn-outline-dark">Create Profile to Make Reservation</a>
                    {% endif %}                </div>
            </form>
            <div style="margin-top: 20px;" class="alert alert-secondary">
                <strong>Reservation Policy:</strong>
                <ul>
                    <li>Reservations can be made up to one day in advance.</li>
                    <li>No cancellations within 2 days of the reservation date.</li>
                    <li>Modify or cancel your reservation at least 2 days in advance.</li>
                    <li>Please arrive on time. We may not hold your table for more than 15 minutes.</li>
                    <li>Cancellation within 2 days incurs a €5 fee.</li>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

reservations/templates/reservations/user_reservations.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>My Reservations</h1>
    <ul>
        {% for reservation in reservations %}
            <li>
                Reservation for {{ reservation.user.username }} on {{ reservation.date }} at {{ reservation.time }}
                <form method="post" action="{% url 'reservations:cancel_reservation' reservation.id %}" >
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Cancel</button>
                </form>
            </li>
        {% empty %}
            <p>You have no reservations.</p>
        {% endfor %}
    </ul>
</div>
{% endblock %}