accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/create/', views.create_profile, name='create_profile'),
    path('profile/', views.profile_detail, name='profile_detail'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

cafe/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('menu/', include('menu.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'),
         namespace='accounts')),
    path('reservations/',
         include('reservations.urls', namespace='reservations')),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('reserve/', views.reserve_table, name='reserve_table'),
    path('user_reservations/',
         views.user_reservations, name='user_reservations'),
    path('cancel_reservation/<int:reservation_id>/',
         views.cancel_reservation, name='cancel_reservation'),
    path('make_reservation/', views.reserve_table, name='make_reservation'),
    path('reserve_confirmation/',
         views.reserve_table, name='reserve_confirmation'),
    path('edit/<int:reservation_id>/',
         views.edit_reservation, name='edit_reservation'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    """
    Represents a user profile linked to the Django User model.
    It stores additional information
    about the user such as phone number, address, email, profile image,
    and email verification status with text.
    The image is resized to 300x300 pixels with 75% quality in WEBP format.
    """
    user = models.OneToOneField(
        User, related_name="profile",
        on_delete=models.CASCADE,
        primary_key=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    email = models.EmailField(default='')
    image = ResizedImageField(
        size=[300, 300],
        quality=75,
        upload_to='profile_images/',
        force_format="WEBP",
        blank=True,
        null=True,
        )
    updated_on = models.DateField(auto_now=True)
    is_email_verified = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Signal handler to create a UserProfile instance automatically
    when a new User instance is created.
    This ensures that each User has an associated UserProfile,
    for storing additional information.
    """
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """
    Signal handler to save the UserProfile instance
    automatically whenever the User instance is saved.
    This keeps the UserProfile information up to date,
    with the User instance changes.
    """
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    """
    Form for updating user profile information.
    Allows users to update their:
    phone number, address, profile image, and optionally, their email.
    """
    new_email = forms.EmailField(label='New Email', required=False)

    def clean_new_email(self):
        new_email = self.cleaned_data.get('new_email')
        if User.objects.filter(email=new_email).exists():
            raise forms.ValidationError("This email is already in use.")
        return new_email

    class Meta:
        model = UserProfile
        fields = ['phone_number', 'address', 'image', 'new_email']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserProfileForm
from .models import UserProfile

from django.contrib.auth.decorators import login_required
from reservations.models import Reservation
from django.contrib import messages
from allauth.account.utils import send_email_confirmation
from allauth.account.models import EmailAddress
from django.contrib.auth.models import User
from django.db import transaction


@login_required
def create_profile(request):
    """
    View for creating a new user profile. If the user already has a profile,
    redirects to the profile detail page. On POST, validates and saves the new
    profile form, then redirects to the profile detail page.
    Otherwise, displays a blank profile form.
    """
    if UserProfile.objects.filter(user=request.user).exists():
        return redirect('accounts:profile_detail')

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('accounts:profile_detail')
    else:
        form = UserProfileForm()
    return render(request, 'accounts/profile_form.html', {'form': form})


@login_required
def profile_detail(request):
    """
    View for displaying the details of the user's profile,
    including any reservations.
    A permanent text showing users always to make sure to verify their email,
    if they have updated their email.
    If the profile does not exist, redirects to the profile creation page.
    """
    user = request.user
    if not user.is_active:
        messages.error(
            request, 'Make sure to verify email to view your profile')
        return redirect('home')

    try:
        profile = UserProfile.objects.get(user=request.user)
        reservations = Reservation.objects.filter(user=request.user)

        # Fetch email verification status
        email_verified = EmailAddress.objects.filter(
            user=request.user, verified=True).exists()

    except UserProfile.DoesNotExist:
        return redirect('accounts:create_profile')

    return render(
        request, 'accounts/profile_detail.html',
        {'profile': profile, 'reservations': reservations})


@login_required
def edit_profile(request):
    """
    View for editing an existing user profile.
    On POST, updates the user's profile with the form data.
    If a new email is provided, triggers an email verification process.
    On success, redirects to the profile detail page.
    Otherwise, displays the profile form pre-filled with user's profile data.
    """
    profile = get_object_or_404(UserProfile, user=request.user)
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            # Check if a new email address is provided
            new_email = form.cleaned_data.get('new_email')
            if new_email:
                # Trigger verification email sending process
                user.email = new_email
                user.save()
                send_email_confirmation(request, user)

            form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('accounts:profile_detail')
    else:
        form = UserProfileForm(instance=profile)
    return render(request, 'accounts/profile_form.html', {'form': form})


@login_required
def delete_profile(request):
    """
    View for deleting the user's profile and users reservations.
    On POST, deletes the user's profile and all associated reservations,
    within an atomic transaction to ensure data integrity, then redirects to
    the home page. Otherwise, displays a confirmation prompt.
    """
    if request.method == 'POST':
        # If the user confirms deletion,
        # delete the profile and associated reservations
        profile = request.user.profile
        reservations = Reservation.objects.filter(user=request.user)
        with transaction.atomic():
            profile.delete()
            reservations.delete()
        # Optionally, you can add a message to indicate successful deletion
        messages.success(request, 'Your profile has been deleted.')
        return redirect('home')  # Redirect to home page or wherever you want
    return render(
        request,
        'accounts/profile_confirm_delete.html', {'delete_account': False})


@login_required
def delete_account(request):
    """
    View for deleting the user's account.
    On POST, deletes the user's account and redirects to the home page.
    Otherwise, displays a confirmation prompt indicating account deletion.
    """
    if request.method == 'POST':
        # If the user confirms deletion, delete the entire account
        request.user.delete()
        return redirect('home')  # Redirect to home page or wherever you want
    return render(
        request,
        'accounts/profile_confirm_delete.html', {'delete_account': True})

accounts/templates/accounts/profile_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    <h2 class="mb-0">{% if delete_account %}Confirm Account Deletion{% else %}Confirm Profile Deletion{% endif %}</h2>
                </div>
                <div class="card-body">
                    <p class="lead">{% if delete_account %}Are you sure you want to delete your account?{% else %}Are you sure you want to delete your profile?{% endif %}</p>
                    <!-- Warning text if deleting profile or account-->
                    <p class="text-danger">Warning: Deleting your {% if delete_account %}account{% else %}profile{% endif %} will also delete all associated reservations.</p> 
                    <form method="post" class="mt-3">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-danger mr-2">Confirm</button>
                            <a href="{% if delete_account and delete_profile %}{% url 'home' %}{% else %}{% url 'accounts:profile_detail' %}{% endif %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile_create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h2>Create Profile</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'accounts:create_profile' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-dark btn-sm">Create Profile</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container mt-4">
    <!-- Profile Information -->
    <div class="row">
        <div class="col-md-6">
            <h2>Profile Information</h2>
            <div class="card mb-4">
                <div class="card-body">
                    {% if profile %}
                        <h2>My Profile</h2>
                        <!-- Profile information -->
                        <!-- Image -->
                        {% if profile.image %}
                            <img src="{{ profile.image.url }}" alt="Profile Image">
                        {% else %}
                            <img src="{% static 'images/default_.webp' %}" alt="Default Profile Image" style="width: 300px; height: auto;">
                        {% endif %}
                        <!-- Name, Phone, Address, Email -->
                        <p><strong>Name:</strong> {{ profile.user.username|default:"No name set" }}</p>
                        <p><strong>Phone:</strong> {{ profile.phone_number }}</p>
                        <p><strong>Address:</strong> {{ profile.address }}</p>
                        <p><strong>Email:</strong> {{ profile.user.email }}</p>
                        <!-- Message -->
                        <p>Make sure to verify your email if you have updated it. Check your inbox for the verification email.</p>
                        <!-- Buttons for actions -->
                        {% if request.user == profile.user %}
                            <div>
                                <a href="{% url 'accounts:delete_profile' %}" class="btn btn-outline-danger btn-sm">Delete Profile</a>
                                <a href="{% url 'accounts:delete_account' %}" class="btn btn-outline-danger btn-sm">Delete Account</a>
                                <a href="{% url 'accounts:edit_profile' %}" class="btn btn-outline-dark btn-sm">Edit</a>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- My Reservations -->
        <div class="col-md-6">
            <h2>My Reservations</h2>
            <div class="card">
                <div class="card-body">
                    <ul class="list-group">
                        <!-- Display reservations -->
                        {% if reservations %}
                            {% for reservation in reservations %}
                                <li class="list-group-item">
                                    <strong>Reservation for {{ reservation.date }} at {{ reservation.time }}</strong>
                                    <div class="btn-group" role="group">
                                        <!-- Cancel and Edit buttons -->
                                        <a href="{% url 'reservations:cancel_reservation' reservation.id %}" class="btn btn-outline-danger btn-sm">Cancel</a>
                                        <a href="{% url 'reservations:edit_reservation' reservation.id %}" class="btn btn-outline-dark btn-sm">Edit</a>
                                    </div>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item">No reservations yet.</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4 mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-10">
            <h1>{% if form.instance.pk %}Edit Profile{% else %}Create Profile{% endif %}</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.phone_number|as_crispy_field }}
                <br>
                {{ form.image|as_crispy_field }}
                <br>
                {{ form.address|as_crispy_field }}
                <br>
                <label for="change_email_trigger">If you want to change email, click here:</label>
                <button type="button" id="change_email_trigger" class="btn btn-outline-dark btn-sm">Change Email</button><br>
                <div id="new_email_section" style="display: none;">
                    {{ form.new_email|as_crispy_field }}
                    <br>
                    <p>Make sure to verify your email if you change your email. Check your inbox for the verification email.</p>
                </div>
                <!-- Display email as read-only text only if its verified -->
                <button type="submit" class="btn btn-dark">{% if form.instance.pk %}Save{% else %}Create Profile{% endif %}</button>
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const changeEmailTrigger = document.getElementById('change_email_trigger');
        const newEmailSection = document.getElementById('new_email_section');
    
        changeEmailTrigger.addEventListener('click', function() {
            if (newEmailSection.style.display === 'none') {
                newEmailSection.style.display = 'block';
            } else {
                newEmailSection.style.display = 'none';
            }
        });
    });
</script>

{% endblock %}