accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/create/', views.create_profile, name='create_profile'),
    path('profile/', views.profile_detail, name='profile_detail'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

cafe/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('menu/', include('menu.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'),
         namespace='accounts')),
    path('reservations/',
         include('reservations.urls', namespace='reservations')),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_menu/', views.add_menu_item, name='add_menu_item'),
    path('menu/', views.menu_list, name='menu_list'),
]

templates/includes/footer.html
{% load static %}

<footer class="bg-dark text-white text-center py-3">
    <p>&copy; 2024 Sahara Cafe & Beans</p>
</footer>

templates/includes/header.html
{% load static %}
<header>
    {% with request.resolver_match.url_name as url_name %}
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <!-- Logo -->
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.webp' %}" alt="Logo for Sahara Cafe & Beans" class="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Nav items -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'home' %}active{% endif %}" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'menu_list' %}active{% endif %}" href="{% url 'menu:menu_list' %}">Menu</a>
                            <li class="nav-item">
                            <a class="nav-link {% if url_name == 'contact' %}active{% endif %}" href="{% url 'contact' %}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'about' %}active{% endif %}" href="{% url 'about' %}">About</a>
                        </li>
                    </ul>
                    <!-- Login and Signup buttons -->
                    <ul class="navbar-nav">
                        {% if request.user.is_authenticated %}
                        {% if request.user.profile %}
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'profile_detail' %}active{% endif %}" href="{% url 'accounts:profile_detail' %}">Profile</a>
                        </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'create_profile' %}active{% endif %}" href="{% url 'accounts:create_profile' %}">Create Profile</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'accounts_logout' %}active{% endif %}" href="/accounts/logout/">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if url_name == 'accounts_login' %}active{% endif %}" href="/accounts/login/">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark {% if url_name == 'accounts_signup' %}active{% endif %}" href="/accounts/signup/" role="button">Signup</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {% endwith %}
</header>